### ISSUE TITLE
Extracting data from population entities

### ISSUE THREAD

**Issue by emanuele45** [scottfr/simulation#2]
Hi,

I was playing with agents and I'm trying to understand if it is possible to obtain the internal values of each single entity of a population.
I tried to look into the documentation and the code, but I got lost rather quickly.
For example, based on this example I put together:
https://insightmaker.com/insight/7zi54imIEuw9WI0ZrpGPLi/Test-Agent
would it be possible from Model to access the values of "Stock" for each of the 100 entities consisting the size of the population?

Thanks for any hint on that!

**Comment by scottfr** [comment]
You want to use the `Value` function (see https://insightmaker.com/docs/functions for a list of all functions). 

You can wire things up similarly to how `Percent Infected` is connected in this model: https://insightmaker.com/insight/5s50cHzvjblXrth2RTBiwp/Agent-Based-Disease-Simulation

**Comment by emanuele45** [comment]
AHA!
Thanks for the hints, now I got it!

Thank you very much for both the great tool and support!
